INSERT INTO "Competition" (
    "id",
    "slug",
    "title",
    "shortTitle",
    "description",
    "venue",
    "startDate",
    "endDate",
    "competitionYear",
    "status",
    "isPublished",
    "registrationOpen",
    "resultsPublished",
    "paymentQrPath",
    "heroImagePath",
    "config"
) VALUES (
    '37th-salvo-cup',
    '37th-salvo-cup',
    '37th Salvo Cup',
    '37th Salvo Cup',
    'Four days of precision shooting, championship rewards, and cash prizes at Salvo Shooters Arena.',
    'Salvo Shooters Arena, Sector 86, Mohali',
    '2026-08-06T00:00:00.000Z',
    '2026-08-09T00:00:00.000Z',
    2026,
    'open',
    true,
    true,
    false,
    '/upi-scanner.png',
    '/37th-salvo-cup-hero.png',
    '{
      "competitionYear": 2026,
      "entryFee": 1000,
      "littleChampEntryFee": 800,
      "feesByRuleSet": { "NR": null, "ISSF": null },
      "allowedPaymentModes": ["upi", "cash"],
      "noCashPrizes": false,
      "awardsNote": "All winners receive an official event medal, championship trophy, and premium gift hamper in addition to the listed cash prize.",
      "matchStartTime": "8:00 AM",
      "minAge": null,
      "requiredDocuments": { "birthCertificate": false, "aadhaarCard": false },
      "requiresGuardianDetails": false,
      "requiresAddress": false,
      "teamEntriesEnabled": true,
      "rules": [],
      "registrationNotes": [],
      "contactName": null,
      "contactPhone": null,
      "detailDefaults": { "firstSightingTimes": { "NR": "08:30", "ISSF": "08:30" } },
      "events": [
        { "id": "issf-air-pistol", "discipline": "pistol", "ruleSet": "ISSF", "title": "ISSF Air Pistol", "prizes": [11000, 7100, 5100] },
        { "id": "nr-air-pistol", "discipline": "pistol", "ruleSet": "NR", "title": "NR Air Pistol", "prizes": [7100, 5100, 3100] },
        { "id": "issf-air-rifle", "discipline": "rifle", "ruleSet": "ISSF", "title": "ISSF Air Rifle", "prizes": [7100, 5100, 3100] },
        { "id": "nr-air-rifle", "discipline": "rifle", "ruleSet": "NR", "title": "NR Air Rifle", "prizes": [5100, 3100, 2100] }
      ],
      "slotOptions": [
        { "date": "2026-08-06", "label": "August 6, 2026", "slots": ["8:00 AM - 11:00 AM", "11:00 AM - 2:00 PM", "2:00 PM - 5:00 PM", "5:00 PM - 8:00 PM"] },
        { "date": "2026-08-07", "label": "August 7, 2026", "slots": ["8:00 AM - 11:00 AM", "11:00 AM - 2:00 PM", "2:00 PM - 5:00 PM", "5:00 PM - 8:00 PM"] },
        { "date": "2026-08-08", "label": "August 8, 2026", "slots": ["8:00 AM - 11:00 AM", "11:00 AM - 2:00 PM", "2:00 PM - 5:00 PM", "5:00 PM - 8:00 PM"] },
        { "date": "2026-08-09", "label": "August 9, 2026", "slots": ["8:00 AM - 11:00 AM", "11:00 AM - 2:00 PM", "2:00 PM - 4:00 PM"] }
      ]
    }'::jsonb
)
ON CONFLICT ("slug") DO UPDATE SET
    "title" = EXCLUDED."title",
    "shortTitle" = EXCLUDED."shortTitle",
    "description" = EXCLUDED."description",
    "venue" = EXCLUDED."venue",
    "startDate" = EXCLUDED."startDate",
    "endDate" = EXCLUDED."endDate",
    "competitionYear" = EXCLUDED."competitionYear",
    "status" = EXCLUDED."status",
    "isPublished" = EXCLUDED."isPublished",
    "registrationOpen" = EXCLUDED."registrationOpen",
    "resultsPublished" = EXCLUDED."resultsPublished",
    "paymentQrPath" = EXCLUDED."paymentQrPath",
    "heroImagePath" = EXCLUDED."heroImagePath",
    "config" = EXCLUDED."config",
    "updatedAt" = CURRENT_TIMESTAMP;
